universe                = docker
docker_image            = adv010/misr_tf:v2
executable              = main_cifar.py
output                  = c2d_train.out
error                   = c2d_train.err
log                     = c2d_train.log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 1
request_memory = 15.8G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1
