universe 		        = docker
docker_image 		    = pytorch/pytorch:latest
executable              = pytorch_classifier.py
output                  = pytorch_classifier.$(ClusterId).$(ProcId).out
error                   = pytorch_classifier.$(ClusterId).$(ProcId).err
log                     = pytorch_classifier.$(ClusterId).log
should_transfer_files   = YES
request_GPUs = 1
request_CPUs = 1
request_memory = 1G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1
